version: 1.0.{build}

branches:
  only:
    - master
    - develop
    - ksidirop/mzr-29-migrate-to-dotnet9
image:
  - Visual Studio 2022

clone_depth: 1 # platform: Any CPU
configuration: Release
solution_filepath: Code/MazeRunner.slnx

build_script: # restores packages automatically
  - sh: dotnet                               \
      build                                  \
      "$(solution_filepath)"                 \
      --configuration "$(configuration)"
test_script:
  - sh: dotnet                               \
      test                                   \
      "$(solution_filepath)"                 \
      --no-build                             \
      --configuration "$(configuration)"     \
      --logger "console;verbosity=normal"

artifacts:
  - path: Code/MazeRunner.Cli/bin/$(configuration)/**/*
    name: MazeRunner.Cli
  - path: Code/MazeRunner.TestbedUI/bin/$(configuration)/**/*
    name: MazeRunner.TestbedUI
