<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="TestArtifacts\**\*" />
        <EmbeddedResource Update="Properties\Resources.resx">
            <SubType>Designer</SubType>
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Moq" />
        <PackageReference Include="Castle.Core" />
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />

        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit.Analyzers">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
            <AutoGen>True</AutoGen>
            <DesignTime>True</DesignTime>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MazeRunner.Contracts\MazeRunner.Contracts.csproj" />
        
        <ProjectReference Include="..\MazeRunner.Cli\MazeRunner.Cli.csproj" />
        <ProjectReference Include="..\MazeRunner.Mazes\MazeRunner.Mazes.csproj" />
        <ProjectReference Include="..\MazeRunner.EnginesFactory\MazeRunner.EnginesFactory.csproj" />
        <ProjectReference Include="..\MazeRunner.Engines.SimpleMazeRunner\MazeRunner.Engines.SimpleMazeRunner.csproj" />
    </ItemGroup>

</Project>
