<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md">
            <Link>README.md</Link>
        </None>
    </ItemGroup>

    <ItemGroup>
        <!-- Files dependent on eachother -->
        <Compile Update="**\CliControllerEngine.*.cs">
            <DependentUpon>CliControllerEngine.cs</DependentUpon>
        </Compile>
    </ItemGroup>
    

    <ItemGroup>
        <ProjectReference Include="..\MazeRunner.Injectors.Autofac\MazeRunner.Injectors.Autofac.csproj" />
        <ProjectReference Include="..\MazeRunner.Mazes\MazeRunner.Mazes.csproj"/>
        <ProjectReference Include="..\MazeRunner.EnginesFactory\MazeRunner.EnginesFactory.csproj"/>

        <!-- it is necessary to include this reference to force the project to spawn its dll under the output folder so that we can scan the engines it provides upon launching -->
        <ProjectReference Include="..\MazeRunner.Engines.SimpleMazeRunner\MazeRunner.Engines.SimpleMazeRunner.csproj" />

        <!-- INJECTORS REGISTRIES -->
        <ProjectReference Include="..\MazeRunner.Mazes.Injections\MazeRunner.Mazes.Injections.csproj"/>
        <ProjectReference Include="..\MazeRunner.EnginesFactory.Injections\MazeRunner.EnginesFactory.Injections.csproj"/>
    </ItemGroup>

</Project>
