<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\MazeRunner.Contracts\MazeRunner.Contracts.csproj" />
      <ProjectReference Include="..\MazeRunner.Engines.Contracts\MazeRunner.Engines.Contracts.csproj" />
      <ProjectReference Include="..\MazeRunner.Mazes.Contracts\MazeRunner.Mazes.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="MazeRunner.Tests" />
    </ItemGroup>

</Project>
