<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="Autofac" Version="8.3.0" />
        <PackageVersion Include="System.Reactive" Version="6.0.1" />
        <PackageVersion Include="JetBrains.Annotations" Version="2025.2.0" />
        <PackageVersion Include="Microsoft.Extensions.FileSystemGlobbing" Version="9.0.7" />
    </ItemGroup>

    <!-- MazeRunner.Tests -->
    <ItemGroup>
        <PackageVersion Include="Moq" Version="4.20.72" />
        <PackageVersion Include="Castle.Core" Version="5.2.1" />
        <PackageVersion Include="FluentAssertions" Version="[7.2.0, 8)" />
        <PackageVersion Include="coverlet.collector" Version="6.0.4" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        
        <PackageVersion Include="NUnit" Version="4.3.2" />
        <PackageVersion Include="NUnit.Analyzers" Version="4.9.2" />
        <PackageVersion Include="NUnit3TestAdapter" Version="5.0.0" />
    </ItemGroup>

</Project>
