<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\MazeRunner.Contracts\MazeRunner.Contracts.csproj" />
      <ProjectReference Include="..\MazeRunner.Mazes.Contracts\MazeRunner.Mazes.Contracts.csproj" />
      <ProjectReference Include="..\MazeRunner.Utils\MazeRunner.Utils.csproj" />
    </ItemGroup>

</Project>
