//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazeRunner.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MazeRunner.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SXXX
        ///__XX
        ///X__X
        ///XX_G.
        /// </summary>
        internal static string EIT_Maze001_Diagonal {
            get {
                return ResourceManager.GetString("EIT_Maze001_Diagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S______
        ///XXXXXX_
        ///X____X_
        ///X_XX_X_
        ///X_XG_X_
        ///X_XXXX_
        ///X______
        ///.
        /// </summary>
        internal static string EIT_Maze002_GTrap {
            get {
                return ResourceManager.GetString("EIT_Maze002_GTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G______
        ///XXXXXX_
        ///X____X_
        ///X_XX_X_
        ///X_XS_X_
        ///X_XXXX_
        ///X______
        ///.
        /// </summary>
        internal static string EIT_Maze003_GEscape {
            get {
                return ResourceManager.GetString("EIT_Maze003_GEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _______________S_____________X____
        ///XX_XXX_XXXXXXXXXXXXXXXXXXXXXXX__X_
        ///___X_X_X_______________________XX_
        ///_X_X_____XXX_XX_XXXXXX_XXXXXXXX_X_
        ///___X_X_X_X____X_X___GX____XXX___X_
        ///_X_XXX_XXX_XX_X_X_XXXX_XX_XX__XXX_
        ///XX_____XXX_____________XXXXX______.
        /// </summary>
        internal static string EIT_Maze004_LabyrinthSolvable {
            get {
                return ResourceManager.GetString("EIT_Maze004_LabyrinthSolvable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _______________S_____________X____
        ///XX_XXX_XXXXXXXXXXXXXXXXXXXXXXX__X_
        ///___X_X_X_______________________XX_
        ///_X_X_____XXX_XX_XXXXXX_XXXXXXXX_X_
        ///___X_X_X_X____X_X__XGX____XXX___X_
        ///_X_XXX_XXX_XX_X_X_XXXX_XX_XX__XXX_
        ///XX_____XXX_____________XXXXX______.
        /// </summary>
        internal static string EIT_Maze005_LabyrinthUnsolvable {
            get {
                return ResourceManager.GetString("EIT_Maze005_LabyrinthUnsolvable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MFT_Empty {
            get {
                return ResourceManager.GetString("MFT_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___!@#SGX.
        /// </summary>
        internal static string MFT_InvalidChars {
            get {
                return ResourceManager.GetString("MFT_InvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___SG___
        ///_______
        ///.
        /// </summary>
        internal static string MFT_JaggedMaze {
            get {
                return ResourceManager.GetString("MFT_JaggedMaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG.
        /// </summary>
        internal static string MFT_MinValid_1x2 {
            get {
                return ResourceManager.GetString("MFT_MinValid_1x2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S
        ///G.
        /// </summary>
        internal static string MFT_MinValid_2x1 {
            get {
                return ResourceManager.GetString("MFT_MinValid_2x1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___G__
        ///.
        /// </summary>
        internal static string MFT_NoEntrypoint {
            get {
                return ResourceManager.GetString("MFT_NoEntrypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___S__
        ///.
        /// </summary>
        internal static string MFT_NoExitpoint {
            get {
                return ResourceManager.GetString("MFT_NoExitpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___SG__
        ///
        ///_______
        ///.
        /// </summary>
        internal static string MFT_StrayNewLines {
            get {
                return ResourceManager.GetString("MFT_StrayNewLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _S__
        ///_XX_
        ///__G_.
        /// </summary>
        internal static string MFT_Valid_3x4 {
            get {
                return ResourceManager.GetString("MFT_Valid_3x4", resourceCulture);
            }
        }
    }
}
